### ISSUE TITLE
Cancelled order does not refund

### ISSUE THREAD

**Issue by orjhor** [krokedil/dibs-easy-for-woocommerce#130]
Hi,
Any reason why a cancelled order is not refunded automatically?
I believe this is common in most payment gateway plugins?`

Thanks!

**Comment by NiklasHogefjord** [comment]
Hi,

How do you mean, that a _Cancelled_ order in WooCommerce results in a refund in Nets system?

**Comment by orjhor** [comment]
For instance, if a Woocommerce order has been made, and payed with Nets, the status of that order is "Pending". 
If the customer then decides to cancel the order and we set the order status to "Cancelled", then the payed amount is not automatically refunded. Instead we have to create a manual refund on the order itself.

This might just be an issue when the amount has been captured, as I figure the amount will only be reserved for so long before being released.

**Comment by NiklasHogefjord** [comment]
Hi @orjhor,
Sorry for the late reply even in this issue.

If an order has been made, it should not have the status "Pending". The order status in Woo should be "Processing" or "Completed". If it is still "Pending" you probably have an issue with your integration.

**Comment by orjhor** [comment]
Sorry, I had a typo in my last comment ("Pending" should be "Processing"). Fixed now, please read again - thanks :-)

**Comment by NiklasHogefjord** [comment]
Sorry for the veeeeery late reply here @orjhor.

If we're talking about a Swish payment for instance (a payment method that instantly captures the amount) then you need to _Refund_ the order in Woo to be able to return the money to the customer (instead of just changing the order status to _Cancelled_).

If we are talking about an invoice payment or card payment (that is captured when order status is set to _Completed_) then you can change the status from _Processing_ to _Cancelled_ and it will cancel the payment in Nets system. This is because the payment itself is still in a "reserved" status in Nets system at this moment.

Do I understand it correctly that you would like to be able to set the status to _Cancelled_ here and the Swish payment should be automatically be refunded/repaid to the customer?

**Comment by NiklasHogefjord** [comment]
I'm closing this for now but feel free to re-open it again if needed.
