### ISSUE TITLE
Terms & Conditions missing?

### ISSUE THREAD

**Issue by jonkristian** [krokedil/dibs-easy-for-woocommerce#33]
When selecting DIBS Easy payment method, the terms and conditions are missing, are they missing for a reason?. Just guessing this might be because the plugin uses an iframe and need to sort things out on a separate page? Is it not possible to add standard checkout features alongside the iframe? One solution I've thought off could be to deactivate payment selection until terms are checked, but interested to know why it's missing.

**Comment by NiklasHogefjord** [comment]
Hi @jonkristian,
Sorry for not getting back to you sooner.

We don't have the WooCommerce terms and conditions checkbox visible when DIBS Easy is the selected payment method. This is because DIBS Easy is an embedded checkout solution that replaces large parts of the checkout page. Terms is one of them.

DIBS have recently changed the layout of the Easy checkout so now there is a checkbox for confirming the terms, both DIBS and the store terms). It looks like this:

![image](https://user-images.githubusercontent.com/985946/48781206-e0e69180-ecdb-11e8-9fec-151ec5de6970.png)

From what I can see this setup solves the same functionality as the regular terms checkbox in WooCommerce checkout does.
